### ISSUE TITLE
怎么让任务执行完后结束

### ISSUE THREAD

**Issue by ppzky** [bbossgroups/hbase-elasticsearch#1]
https://github.com/bbossgroups/hbase-elasticsearch/blob/8f7b5f0054ff3ba0548ec8a7af1d6f7869bda14e/src/main/java/org/frameworkset/elasticsearch/imp/HBase2ESFullDemo.java#L128
这行代码注释后，在后面添加了dataStream.destroy()，然后程序就一直在wait。请问我只想执行一次任务就结束，该怎么操作呢？

**Comment by yin-bp** [comment]
@ironbang 这个要看看进程线程堆栈，是不是还有什么东西没有关闭：
java执行线程堆栈

jtack -l pid

下面的spring boot web服务包含了启停hbase-elasticsearch同步作业的案例：
[https://github.com/bbossgroups/springboot-elasticsearch-webservice](https://github.com/bbossgroups/springboot-elasticsearch-webservice)
